spring:
  application:
    name: gateway-service

#  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri: lb://auth-service # service name
#          predicates:
#            - Path=/auth-service/** # url pattern

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
