spring:
  application:
    name: contact-service
  mvc:
    servlet:
      path: /contact-service

server:
  port: 0

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka