spring:
  application:
    name: profile-composite-service
  mvc:
    servlet:
      path: /profile-composite-service

server:
  port: 0


eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka